name: Feature request
description: Suggest something Scissor should do.
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like to do?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is it useful?
